### ISSUE TITLE
Include script in repeatable snippet

### ISSUE THREAD

**Issue by ChaseGiunta** [jenwachter/jquery.repeatable#3]
Is this possible? The javascript would have dynamic values and would use `{?}` within each `<script>` block.

**Comment by jenwachter** [comment]
The repeatable snippet is itself inside a `<script>` tag, so I believe what you are asking for is not possible since `<script>` tags cannot be nested inside one another.

Although, after a quick search, I found this method of tricking browsers to allow you to do what you are asking: http://www.joelpeterson.com/blog/2011/04/nested-script-tags-javascript-begets-javascript/

I don't vouch for that solution, but it might help.

Closing this issue as this problem is not with the lib.
